export const WARHAMMER_40K_ARMIES = [
  'Astra Militarum',
  'Chaos Knights',
  'Chaos Space Marines',
  'Custodes',
  'Dark Eldar',
  'Eldar',
  'Grey Knights',
  'Genestealer Cults',
  'Imperial Guard',
  'Imperial Knights',
  'Mechanicus',
  'Necrons',
  'Orks',
  'Space Marines',
  'Tau Empire',
  'Tyranids',
  'Leagues of Votann',
  'Sisters of Battle',
  'World Eaters',
  'Thousand Sons',
  'Black Legion',
  'Death Guard',
  'Astra Militarum Renegades',
] as const;
